In [1]:
import pandas as pd
import numpy as np
from statsmodels.tsa.arima_model import ARIMA
from pathlib import Path
%matplotlib inline

In [2]:
filepath = Path('../data/data.csv')
data = pd.read_csv(filepath)

In [3]:
data

,Player,Pos,Year,Week,Team,Opponent Abbrev,Date,Game ID,H/A,OT,...,FG 0-19,FG 20-29,FG 30-39,FG 40-49,FG 50+,XPM,XPA,Pnt,Yds,Y/P
0,Aaron Rodgers,QB,2019,1,GNB,CHI,2019-09-05,201909050chi,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aaron Jones,RB,2019,1,GNB,CHI,2019-09-05,201909050chi,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Marquez Valdes-Scantling,WR,2019,1,GNB,CHI,2019-09-05,201909050chi,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Davante Adams,WR,2019,1,GNB,CHI,2019-09-05,201909050chi,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jimmy Graham,TE,2019,1,GNB,CHI,2019-09-05,201909050chi,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30687,Connor Barth,K,2015,17,TAM,CAR,2016-01-03,201601030car,A,NaN,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,NaN
30688,Graham Gano,K,2015,17,CAR,TAM,2016-01-03,201601030car,H,NaN,...,0.0,0.0,0.0,1.0,0.0,5.0,5.0,0.0,0.0,NaN
30689,Sebastian Janikowski,K,2015,17,OAK,KAN,2016-01-03,201601030kan,A,NaN,...,0.0,1.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,NaN
30690,Blair Walsh,K,2015,17,MIN,GNB,2016-01-03,201601030gnb,A,NaN,...,0.0,0.0,2.0,0.0,0.0,2.0,2.0,0.0,0.0,NaN
30691,Mason Crosby,K,2015,17,GNB,MIN,2016-01-03,201601030gnb,H,NaN,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,NaN

In [4]:
# #Breaking data up by position so that I can drop useless columns for that position
#commented out for now so I can run all cells 
# def positions():
#     qb_data = []
#     rb_data = []
#     wr_data = []
#     te_data = []
#     fb_data = []
#     dst_data = []
#     k_data = []
    
    
#     for i, row in data.iterrows():
#         if data.at[i, 'Pos'] == 'QB':
#             qb_data.append(row)
        
#         elif data.at[i, 'Pos'] == 'RB':
#             rb_data.append(row)
            
#         elif data.at[i, 'Pos'] == 'WR':
#             wr_data.append(row)
        
#         elif data.at[i, 'Pos'] == 'TE':
#             te_data.append(row)
        
#         elif data.at[i, 'Pos'] == 'FB':
#             fb_data.append(row)
            
#         elif data.at[i, 'Pos'] == 'DST':
#             dst_data.append(row)
            
#         else:
#             k_data.append(row)
            
            
#     qb_df = pd.DataFrame(qb_data)        
#     rb_df = pd.DataFrame(rb_data)
#     wr_df = pd.DataFrame(wr_data)
#     te_df = pd.DataFrame(te_data)
#     fb_df = pd.DataFrame(fb_data)
#     dst_df = pd.DataFrame(dst_data)
#     k_df = pd.DataFrame(k_data)
    
#     return qb_df, rb_df, wr_df, te_df, fb_df, dst_df, k_df

In [5]:
qb, rb, wr, te, fb, dst, k = positions()

In [6]:
display(qb)

,Player,Pos,Year,Week,Team,Opponent Abbrev,Date,Game ID,H/A,OT,...,FG 0-19,FG 20-29,FG 30-39,FG 40-49,FG 50+,XPM,XPA,Pnt,Yds,Y/P
0,Aaron Rodgers,QB,2019,1,GNB,CHI,2019-09-05,201909050chi,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Mitchell Trubisky,QB,2019,1,CHI,GNB,2019-09-05,201909050chi,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Marcus Mariota,QB,2019,1,TEN,CLE,2019-09-08,201909080cle,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Ryan Tannehill,QB,2019,1,TEN,CLE,2019-09-08,201909080cle,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Baker Mayfield,QB,2019,1,CLE,TEN,2019-09-08,201909080cle,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26225,Joe Webb,QB,2015,17,CAR,TAM,2016-01-03,201601030car,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26226,Derek Carr,QB,2015,17,OAK,KAN,2016-01-03,201601030kan,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26237,Alex Smith,QB,2015,17,KAN,OAK,2016-01-03,201601030kan,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26249,Teddy Bridgewater,QB,2015,17,MIN,GNB,2016-01-03,201601030gnb,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26260,Aaron Rodgers,QB,2015,17,GNB,MIN,2016-01-03,201601030gnb,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
qb.drop([col for col in qb.columns if 'FG' in col], axis=1, inplace=True)
#qb.drop(['Game ID'], axis=1, inplace=True)
# Okay theres way too many rows with different names, this will be way faster manually
qb.to_csv('qb_data.csv')

In [12]:
# rb.to_csv('rb_data.csv')
# wr.to_csv('wr_data.csv')
# te.to_csv('te_data.csv')
# fb.to_csv('fb_data.csv')
# dst.to_csv('dst_data.csv')
# k.to_csv('k_data.csv')

In [5]:
from pathlib import Path
qb_path = Path('../data/qb_data.csv')
rb_path = Path('../data/rb_data.csv')
wr_path = Path('../data/wr_data.csv')
te_path = Path('../data/te_data.csv')
fb_path = Path('../data/fb_data.csv')
dst_path = Path('../data/dst_data.csv')
k_path = Path('../data/k_data.csv')
qb_clean = pd.read_csv(qb_path, index_col="Player")
rb_clean = pd.read_csv(rb_path, index_col="Player")
wr_clean = pd.read_csv(wr_path, index_col="Player")
te_clean = pd.read_csv(te_path, index_col="Player")
fb_clean = pd.read_csv(fb_path, index_col="Player")
dst_clean = pd.read_csv(dst_path, index_col="Player")
k_clean = pd.read_csv(k_path, index_col="Player")

In [6]:
qb_clean

,Unnamed: 0,Pos,Year,Week,Team,Opponent Abbrev,Date,H/A,OT,Team Score,...,Def Pct,ST Num,ST Pct,DKP,DKSalary,FDP,FDSalary,DK_Total_FP,FD_Total_FP,YH_Total_FP
Player,,,,,,,,,,,,,,,,,,,,,
Aaron Rodgers,0,QB,2019,1,GNB,CHI,9/5/2019,A,NaN,10,...,0%,0,0%,12.92,6500.0,12.92,8200.0,12.92,12.92,12.92
Mitchell Trubisky,9,QB,2019,1,CHI,GNB,9/5/2019,H,NaN,3,...,0%,0,0%,9.22,5700.0,9.22,7200.0,8.22,8.22,9.22
Marcus Mariota,19,QB,2019,1,TEN,CLE,9/8/2019,A,NaN,43,...,0%,0,0%,24.32,5200.0,24.32,6500.0,24.32,24.32,24.32
Ryan Tannehill,29,QB,2019,1,TEN,CLE,9/8/2019,A,NaN,43,...,0%,0,0%,-0.20,4400.0,-0.20,6000.0,-0.20,-0.20,-0.20
Baker Mayfield,31,QB,2019,1,CLE,TEN,9/8/2019,H,NaN,13,...,0%,0,0%,12.40,6400.0,12.40,7900.0,9.40,9.40,12.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Joe Webb,26225,QB,2015,17,CAR,TAM,1/3/2016,H,NaN,38,...,0%,16,67%,0.00,5000.0,0.00,5000.0,0.00,0.00,0.00
Derek Carr,26226,QB,2015,17,OAK,KAN,1/3/2016,A,NaN,17,...,0%,0,0%,11.96,5300.0,11.96,7100.0,10.96,10.96,11.96
Alex Smith,26237,QB,2015,17,KAN,OAK,1/3/2016,H,NaN,23,...,0%,0,0%,18.34,5100.0,18.34,7000.0,16.34,16.34,18.34
Teddy Bridgewater,26249,QB,2015,17,MIN,GNB,1/3/2016,A,NaN,20,...,0%,0,0%,3.16,5100.0,3.16,6800.0,2.16,2.16,3.16
Aaron Rodgers,26260,QB,2015,17,GNB,MIN,1/3/2016,H,NaN,13,...,0%,0,0%,14.84,6800.0,13.84,8300.0,13.84,12.84,13.84